# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [43]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.4.6

In [44]:
data = np.array([1,2,3,4,5])
print(data)
print(len(data))
print(type(data))
print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)

## Exercise 1.4 - Exercises from the Lecture Slides (Pandas)
Sample files created below are saved in a `lecture_data` folder next to this notebook.

### Install and import Pandas

In [45]:
import os
import numpy as np
import pandas as pd
print("Pandas version:", pd.__version__)

os.makedirs("lecture_data", exist_ok=True)

Pandas version: 3.0.3

### Creating a Pandas Series

In [46]:
x = [9, 3, 12]
sr = pd.Series(x)
print(sr)

0     9
1     3
2    12
dtype: int64

### Creating a DataFrame

In [47]:
carsdataset = {
    "cars": ["Ferrari", "Honda", "Toyota"],
    "color": ["Green", "Blue", "Silver"]
}

df = pd.DataFrame(carsdataset)
print(df)

      cars   color
0  Ferrari   Green
1    Honda    Blue
2   Toyota  Silver

### Writing data to a CSV file

In [48]:
data = {'col1': [1, 2, 3], 'col2': ['A', 'B', 'C']}
df = pd.DataFrame(data)

df.to_csv('lecture_data/output.csv', index=False)
print(open('lecture_data/output.csv').read())

col1,col2
1,A
2,B
3,C

### Reading data from a CSV file, viewing and inspecting it
A sample data.csv is created first (from the cars DataFrame) so the read examples can run.

In [49]:
pd.DataFrame({
    "cars": ["Ferrari", "Honda", "Toyota", "BMW", "Ford", "Kia", "Tesla"],
    "color": ["Green", "Blue", "Silver", "Black", "Red", "White", "Grey"],
    "price": [250000, 25000, 30000, 55000, 35000, 22000, 45000]
}).to_csv('lecture_data/data.csv', index=False)

df = pd.read_csv('lecture_data/data.csv')
print(df.to_string())

      cars   color   price
0  Ferrari   Green  250000
1    Honda    Blue   25000
2   Toyota  Silver   30000
3      BMW   Black   55000
4     Ford     Red   35000
5      Kia   White   22000
6    Tesla    Grey   45000

In [50]:
df.head()

      cars   color   price
0  Ferrari   Green  250000
1    Honda    Blue   25000
2   Toyota  Silver   30000
3      BMW   Black   55000
4     Ford     Red   35000

In [51]:
df.tail()

     cars   color  price
2  Toyota  Silver  30000
3     BMW   Black  55000
4    Ford     Red  35000
5     Kia   White  22000
6   Tesla    Grey  45000

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cars    7 non-null      str
 1   color   7 non-null      str
 2   price   7 non-null      int64
dtypes: int64(1), str(2)
memory usage: 365.0 bytes

### Writing and reading Excel workbooks

In [53]:
sample = pd.DataFrame({'Column1': [1, 2, 3], 'Column2': ['A', 'B', 'C'], 'Column3': [10.5, 20.5, 30.5]})

with pd.ExcelWriter('lecture_data/your_file.xlsx') as writer:
    sample.to_excel(writer, sheet_name='Sheet1', index=False)
    sample.to_excel(writer, sheet_name='Sheet2', index=False)

df = pd.read_excel('lecture_data/your_file.xlsx')
df_sheet2 = pd.read_excel('lecture_data/your_file.xlsx', sheet_name='Sheet2')
df_sheet_index_1 = pd.read_excel('lecture_data/your_file.xlsx', sheet_name=1)
df_specific_cols = pd.read_excel('lecture_data/your_file.xlsx', usecols=['Column1', 'Column3'])

print(df, df_sheet2, df_sheet_index_1, df_specific_cols, sep="\n\n")

   Column1 Column2  Column3
0        1       A     10.5
1        2       B     20.5
2        3       C     30.5

   Column1 Column2  Column3
0        1       A     10.5
1        2       B     20.5
2        3       C     30.5

   Column1 Column2  Column3
0        1       A     10.5
1        2       B     20.5
2        3       C     30.5

   Column1  Column3
0        1     10.5
1        2     20.5
2        3     30.5

### Writing and reading JSON

In [54]:
df.to_json('lecture_data/data.json', orient='records')
df_json = pd.read_json('lecture_data/data.json')
print(df_json)

   Column1 Column2  Column3
0        1       A     10.5
1        2       B     20.5
2        3       C     30.5

### Data cleaning: removing and replacing missing values

In [55]:
df_missing = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Score": [85, np.nan, 90, np.nan],
    "City": ["NY", "LA", None, "SF"]
})
print(df_missing, "\n")

new_df = df_missing.dropna()
print("After dropna():\n", new_df, "\n")

filled_df = df_missing.fillna({"Score": 0, "City": "Unknown"})
print("After fillna():\n", filled_df)

  Name  Score City
0    A   85.0   NY
1    B    NaN   LA
2    C   90.0  NaN
3    D    NaN   SF

After dropna():
   Name  Score City
0    A   85.0   NY

After fillna():
   Name  Score     City
0    A   85.0       NY
1    B    0.0       LA
2    C   90.0  Unknown
3    D    0.0       SF

### Example DataFrame for slicing

In [56]:
player_data = [
    ['Player 1', 32, 75, 5428000], ['Player 2', 33, 74, 3428000],
    ['Player 3', 34, 70, 8428000], ['Player 4', 35, 80, 4428000],
    ['Player 5', 36, 100, 4528000], ['Player 6', 38, 72, 7028000],
    ['Player 7', 22, 85, 2528000]
]
df = pd.DataFrame(player_data, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

       Name  Age  Weight   Salary
0  Player 1   32      75  5428000
1  Player 2   33      74  3428000
2  Player 3   34      70  8428000
3  Player 4   35      80  4428000
4  Player 5   36     100  4528000
5  Player 6   38      72  7028000
6  Player 7   22      85  2528000

In [57]:
df1 = df.iloc[0:3]
print(df1)

       Name  Age  Weight   Salary
0  Player 1   32      75  5428000
1  Player 2   33      74  3428000
2  Player 3   34      70  8428000

In [58]:
df1 = df.iloc[:, 0:3]
print(df1)

       Name  Age  Weight
0  Player 1   32      75
1  Player 2   33      74
2  Player 3   34      70
3  Player 4   35      80
4  Player 5   36     100
5  Player 6   38      72
6  Player 7   22      85

In [59]:
value = df.iloc[2, 3]
print("Specific Cell Value:", value)

Specific Cell Value: 8428000

In [60]:
data = df[df['Age'] > 34].iloc[:, :]
print(data)

       Name  Age  Weight   Salary
3  Player 4   35      80  4428000
4  Player 5   36     100  4528000
5  Player 6   38      72  7028000

### Joining DataFrames (by index)

In [61]:
left = pd.DataFrame({'Name': ['Kelly', 'Cat', 'Mat'], 'Age': [25, 30, 35]})
right = pd.DataFrame({'City': ['Boston', 'Denver', 'Austin']})

joined = left.join(right)
print(joined)

    Name  Age    City
0  Kelly   25  Boston
1    Cat   30  Denver
2    Mat   35  Austin

### Merging DataFrames (by a shared column)

In [62]:
employees = pd.DataFrame({
    'EmployeeID': ['E001', 'E002', 'E003', 'E004', 'E005'],
    'Name': ['Kelly', 'Cat', 'Mat', 'Jhon', 'Sam'],
    'DeptID': ['D900', 'D800', 'D900', 'D700', 'D800']})

departments = pd.DataFrame({
    'DeptID': ['D900', 'D700', 'D800'],
    'DeptName': ['Computer', 'Accounts', 'HR']})

merged_df = pd.merge(employees, departments)
print(merged_df)

  EmployeeID   Name DeptID  DeptName
0       E001  Kelly   D900  Computer
1       E002    Cat   D800        HR
2       E003    Mat   D900  Computer
3       E004   Jhon   D700  Accounts
4       E005    Sam   D800        HR

### In-Class Exercise 1: Build and Inspect a DataFrame

In [63]:
students = pd.DataFrame({
    "Student": ["Ana", "Ben", "Chris", "Divya", "Eli"],
    "Quiz1": [88, 76, 92, 81, 69],
    "Quiz2": [84, 80, 95, 79, 74],
    "Attendance": [95, 88, 100, 92, 85]
})

print(students.head(3))
students.info()

print(students[["Student", "Quiz1"]])

high_scores = students[students["Quiz1"] > 80]
print(high_scores)

  Student  Quiz1  Quiz2  Attendance
0     Ana     88     84          95
1     Ben     76     80          88
2   Chris     92     95         100
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     5 non-null      str
 1   Quiz1       5 non-null      int64
 2   Quiz2       5 non-null      int64
 3   Attendance  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 311.0 bytes
  Student  Quiz1
0     Ana     88
1     Ben     76
2   Chris     92
3   Divya     81
4     Eli     69
  Student  Quiz1  Quiz2  Attendance
0     Ana     88     84          95
2   Chris     92     95         100
3   Divya     81     79          92

### In-Class Exercise 2: Clean Missing Data

In [64]:
data = pd.DataFrame({
    "Student": ["Ana", "Ben", "Chris", "Divya", "Eli"],
    "Quiz1": [88, np.nan, 92, 81, 69],
    "Quiz2": [84, 80, np.nan, 79, 74]
})

print("Original rows:", len(data))

dropped = data.dropna()
print("Rows after dropna():", len(dropped))

filled = data.fillna(data[["Quiz1", "Quiz2"]].mean())
print("Rows after fillna():", len(filled))
print(filled)

Original rows: 5
Rows after dropna(): 3
Rows after fillna(): 5
  Student  Quiz1  Quiz2
0     Ana   88.0  84.00
1     Ben   82.5  80.00
2   Chris   92.0  79.25
3   Divya   81.0  79.00
4     Eli   69.0  74.00

**Discussion:** Dropping rows is better when only a few rows are incomplete, the data is plentiful, or a missing value makes the row unreliable (e.g. a missing target label). Filling is better when the dataset is small and every row matters, and a sensible replacement exists (mean/median for scores, 0 for "no purchases", the previous value for time series).

### In-Class Exercise 3: Slice, Filter, and Combine

In [65]:
print(df.iloc[0:4], "\n")

print(df[['Name', 'Age', 'Salary']], "\n")

print("Player 3 salary:", df.iloc[2, 3], "\n")

older = df[df['Age'] > 34]
print(older, "\n")

teams = pd.DataFrame({
    'Name': ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7'],
    'Team': ['Lakers', 'Celtics', 'Bulls', 'Heat', 'Knicks', 'Warriors', 'Nets']
})
final_result = pd.merge(df, teams, on='Name')
print(final_result)

final_result.to_csv('lecture_data/players_final.csv', index=False)
print("\nSaved lecture_data/players_final.csv")

       Name  Age  Weight   Salary
0  Player 1   32      75  5428000
1  Player 2   33      74  3428000
2  Player 3   34      70  8428000
3  Player 4   35      80  4428000

       Name  Age   Salary
0  Player 1   32  5428000
1  Player 2   33  3428000
2  Player 3   34  8428000
3  Player 4   35  4428000
4  Player 5   36  4528000
5  Player 6   38  7028000
6  Player 7   22  2528000

Player 3 salary: 8428000

       Name  Age  Weight   Salary
3  Player 4   35      80  4428000
4  Player 5   36     100  4528000
5  Player 6   38      72  7028000

       Name  Age  Weight   Salary      Team
0  Player 1   32      75  5428000    Lakers
1  Player 2   33      74  3428000   Celtics
2  Player 3   34      70  8428000     Bulls
3  Player 4   35      80  4428000      Heat
4  Player 5   36     100  4528000    Knicks
5  Player 6   38      72  7028000  Warriors
6  Player 7   22      85  2528000      Nets

Saved lecture_data/players_final.csv

### Check Your Understanding
1. **Series vs DataFrame:** a Series is one-dimensional (a single labeled column); a DataFrame is two-dimensional with rows and columns (a table made of Series).
2. **Read a CSV:** `pd.read_csv()`.
3. **`df.iloc[:, 0:3]`:** all rows and the first three columns (positions 0, 1, 2).
4. **Handling missing values:** remove them with `dropna()` or replace them with `fillna()`.
5. **merge() vs slicing:** slicing only selects parts of one DataFrame; `merge()` is used when you need to bring in related data from another DataFrame using a shared key column (e.g. DeptID).

In [66]:
arr = np.array([3, 2, 14, 9, 10, 12])
x = np.where(arr == 9)
print(x)

(array([3]),)

In [67]:
arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])
arr = np.concatenate((arr1, arr2))
print(arr)

[ 9  5  8 55 89 76]